# Generated by Django 4.2.3 on 2023-07-10 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pageTitle', models.CharField(max_length=200, unique=True, verbose_name='Sayfa Başlığı')),
                ('menuTitle', models.CharField(max_length=200, unique=True, verbose_name='Menü Başlığı')),
                ('slug', models.CharField(max_length=200, verbose_name='Slug')),
                ('featuredPhoto', models.CharField(default='headerPhoto', max_length=200, unique=True, verbose_name='Öne Çıkan Görsel')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=1, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar')),
            ],
            options={
                'verbose_name': ' Sayfa',
                'verbose_name_plural': ' Sayfalar',
                'ordering': ['-createdOn'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Şube Adı')),
                ('logo', models.CharField(max_length=200, verbose_name='Logo')),
                ('headerPhoto', models.CharField(default='headerPhoto', max_length=200, unique=True, verbose_name='Header Photo')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('website', models.CharField(default='https://www.digirest.co.uk/', max_length=200, unique=True, verbose_name='Websitesi')),
                ('email', models.CharField(max_length=200, unique=True, verbose_name='E-mail')),
                ('phone', models.CharField(max_length=200, unique=True, verbose_name='Telefon')),
                ('address', models.CharField(max_length=300, unique=True, verbose_name='Adres')),
                ('postcode', models.CharField(max_length=200, unique=True, verbose_name='Posta Kodu')),
                ('district', models.CharField(max_length=200, unique=True, verbose_name='İlçe')),
                ('city', models.CharField(max_length=200, unique=True, verbose_name='Şehir')),
                ('country', models.CharField(max_length=200, unique=True, verbose_name='Ülke')),
                ('facebook', models.CharField(max_length=200, unique=True, verbose_name='Facebook')),
                ('instagram', models.CharField(max_length=200, unique=True, verbose_name='Instagram')),
                ('youtube', models.CharField(max_length=200, unique=True, verbose_name='YouTube')),
                ('twitter', models.CharField(max_length=200, unique=True, verbose_name='Twitter')),
                ('linkedin', models.CharField(max_length=200, unique=True, verbose_name='LinkedIn')),
                ('pinterest', models.CharField(max_length=200, unique=True, verbose_name='Pinterest')),
                ('tripadvisor', models.CharField(max_length=200, unique=True, verbose_name='TripAdvisor')),
                ('telegram', models.CharField(max_length=200, unique=True, verbose_name='Telegram')),
                ('whatsapp', models.CharField(max_length=200, unique=True, verbose_name='WhatsApp')),
                ('mon', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Pazartesi')),
                ('tue', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Salı')),
                ('wed', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Çarşamba')),
                ('thu', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Perşembe')),
                ('fri', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Cuma')),
                ('sat', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Cumartesi')),
                ('sun', models.CharField(default='12:00 - 15:00', max_length=200, unique=True, verbose_name='Pazar')),
                ('createdOn', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updatedOn', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('status', models.IntegerField(choices=[(0, 'Taslak'), (1, 'Yayınla')], default=1, verbose_name='Durum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': ' Şube',
                'verbose_name_plural': ' Şubeler',
                'ordering': ['-createdOn'],
            },
        ),
    ]
