# Generated by Django 4.2.3 on 2023-07-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_page_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(help_text='AVM adını yazınız', max_length=200, unique=True, verbose_name='Şube Adı'),
        ),
    ]
