# Generated by Django 4.2.3 on 2023-07-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_branch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Şube', 'verbose_name_plural': 'Şubeler'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Sayfa', 'verbose_name_plural': 'Sayfalar'},
        ),
    ]
