# Generated by Django 4.2.3 on 2023-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_branch_options_alter_page_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aktif'), (1, 'Pasif')], default=0, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='page',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aktif'), (1, 'Pasif')], default=0, verbose_name='Durum'),
        ),
    ]
