# Generated by Django 4.2.3 on 2023-07-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Satışlar', 'verbose_name_plural': 'Satışlar'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(help_text='Kredi/Banka kartı ile post cihazı üzerinden yapılan satışların toplan tutarı', max_length=200, unique=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='turnover',
            field=models.CharField(default='headerPhoto', max_length=200, unique=True, verbose_name='Ciro'),
        ),
    ]
