# Generated by Django 4.2.3 on 2023-07-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_sales_status_branches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.CharField(max_length=200, unique=True, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='status',
            field=models.IntegerField(choices=[(0, 'Aktif'), (1, 'Pasif')], default=0, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='credit',
            field=models.CharField(help_text='Kredi/Banka kartı ile post cihazı üzerinden yapılan satışların toplan tutarı', max_length=200, unique=True, verbose_name='Kartlı Satış'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(max_length=200, unique=True, verbose_name='Tarih'),
        ),
    ]
