# Generated by Django 4.2.3 on 2023-07-10 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_sales_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='cash',
            field=models.CharField(max_length=200, verbose_name='Nakit Satış'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='credit',
            field=models.CharField(help_text='Kredi/Banka kartı ile post cihazı üzerinden yapılan satışların toplan tutarı', max_length=200, verbose_name='Kartlı Satış'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(max_length=200, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='expense',
            field=models.SlugField(max_length=200, verbose_name='Gider'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='remain',
            field=models.CharField(default='headerPhoto', max_length=200, verbose_name='Kalan'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='turnover',
            field=models.CharField(default='headerPhoto', max_length=200, verbose_name='Ciro'),
        ),
    ]
