# Generated by Django 4.2.3 on 2023-07-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_sales_cash_alter_sales_credit_alter_sales_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Satışlar1', 'verbose_name_plural': 'Satışlar1'},
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.CharField(help_text='Lütfen tarihi belirtiniz.', max_length=200, verbose_name='Tarih'),
        ),
    ]
