# Generated by Django 4.2.3 on 2023-07-12 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_sales_options_alter_sales_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Satışlar', 'verbose_name_plural': 'Satışlar'},
        ),
    ]
