# Generated by Django 4.2.3 on 2023-07-13 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branches',
            options={'ordering': ['-createdOn'], 'verbose_name': 'Şubeler', 'verbose_name_plural': 'Şubeler'},
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='description',
            new_name='addressDescription',
        ),
        migrations.RemoveField(
            model_name='branches',
            name='branchPhoto',
        ),
        migrations.AddField(
            model_name='branches',
            name='photo',
            field=models.CharField(default=121, help_text='Şubenin dıştan görüntüsünü ekleyiniz.', max_length=200, verbose_name='Şube Fotoğrafı'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='email',
            field=models.CharField(max_length=200, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='fri',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Cuma'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='manager',
            field=models.CharField(max_length=200, verbose_name='Şube Müdürü'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='mon',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Pazartesi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='phone',
            field=models.CharField(max_length=200, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sat',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Cumartesi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sun',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Pazar'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='thu',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Perşembe'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='tue',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Salı'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='wed',
            field=models.CharField(default='10:00 - 22:00', max_length=11, verbose_name='Çarşamba'),
        ),
    ]
