# Generated by Django 4.2.3 on 2023-07-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_alter_branches_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=models.TextField(max_length=300, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='addressDescription',
            field=models.TextField(help_text='Şubeye nasıl ulaşılabileceği hakkında bilgi yazın.', verbose_name='Adres Tarifi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.CharField(max_length=200, verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='country',
            field=models.CharField(max_length=200, verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='district',
            field=models.CharField(max_length=200, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='name',
            field=models.CharField(help_text='AVM adını yazınız', max_length=200, verbose_name='Şube(AVM) Adı'),
        ),
    ]
