# Generated by Django 4.2.3 on 2023-07-13 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_alter_branches_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='photo',
            new_name='branchPhoto',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='addressDescription',
            new_name='description',
        ),
    ]
