# Generated by Django 4.2.3 on 2023-07-13 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_rename_photo_branches_branchphoto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branches',
            old_name='description',
            new_name='addressDescription',
        ),
        migrations.RenameField(
            model_name='branches',
            old_name='branchPhoto',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='branches',
            name='fri',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Cuma'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='mon',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Pazartesi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sat',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Cumartesi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='sun',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Pazar'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='thu',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Perşembe'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='tue',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Salı'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='wed',
            field=models.CharField(default='10:00 - 22:00', max_length=13, verbose_name='Çarşamba'),
        ),
    ]
