# Generated by Django 4.2.3 on 2023-07-13 22:34

import cities_light.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('finance', '0013_alter_branches_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='address',
            field=models.CharField(help_text='Maksimum 300 karakter.', max_length=300, verbose_name='Adres'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='addressDescription',
            field=models.CharField(help_text='Maksimum 300 karakter. Şubeye nasıl ulaşılabileceği hakkında bilgi yazın.', max_length=300, verbose_name='Adres Tarifi'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='city',
            field=models.ForeignKey(default=cities_light.models.Region, on_delete=django.db.models.deletion.CASCADE, to='cities_light.region', verbose_name='İl'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='country',
            field=models.ForeignKey(default=cities_light.models.Country, on_delete=django.db.models.deletion.CASCADE, to='cities_light.country', verbose_name='Ülke'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='district',
            field=models.ForeignKey(default=cities_light.models.City, on_delete=django.db.models.deletion.CASCADE, to='cities_light.city', verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='postcode',
            field=models.CharField(help_text='Maksimum 5 karakterli sayı yazınız.', max_length=5, verbose_name='Posta Kodu'),
        ),
    ]
