# Generated by Django 4.2.3 on 2023-07-13 23:31

import cities_light.models
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0014_alter_branches_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
        migrations.AlterField(
            model_name='branches',
            name='district',
            field=models.ForeignKey(default=cities_light.models.SubRegion, on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion', verbose_name='İlçe'),
        ),
    ]
