# Generated by Django 4.2.3 on 2023-07-13 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_alter_branches_author_alter_branches_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(default=datetime.date(2023, 7, 14), help_text='Lütfen tarihi belirtiniz.', verbose_name='Tarih'),
        ),
    ]
