# Generated by Django 4.2.3 on 2023-07-13 23:56

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0016_alter_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='author',
            field=models.ForeignKey(default=django.contrib.auth.models.User, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='date',
            field=models.DateField(help_text='Lütfen tarihi belirtiniz.', verbose_name='Tarih'),
        ),
    ]
