# Generated by Django 4.2.3 on 2023-07-14 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0018_alter_sales_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Kaydeden'),
        ),
    ]
